// <auto-generated />
using System;
using CardDisputePortal.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CardDisputePortal.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260301165708_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CardDisputePortal.Core.Entities.Dispute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EstimatedResolutionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EvidenceAttached")
                        .HasColumnType("bit");

                    b.Property<int>("ReasonCode")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Disputes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("660e8400-e29b-41d4-a716-446655440001"),
                            Details = "Did not make this purchase",
                            EstimatedResolutionDate = new DateTime(2026, 3, 6, 16, 57, 6, 763, DateTimeKind.Utc).AddTicks(1759),
                            EvidenceAttached = false,
                            ReasonCode = 0,
                            Status = 0,
                            SubmittedAt = new DateTime(2026, 2, 19, 16, 57, 6, 763, DateTimeKind.Utc).AddTicks(1356),
                            TransactionId = new Guid("550e8400-e29b-41d4-a716-446655440001"),
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("660e8400-e29b-41d4-a716-446655440002"),
                            Details = "Item never delivered",
                            EstimatedResolutionDate = new DateTime(2026, 3, 11, 16, 57, 6, 763, DateTimeKind.Utc).AddTicks(2140),
                            EvidenceAttached = false,
                            ReasonCode = 3,
                            Status = 1,
                            SubmittedAt = new DateTime(2026, 2, 24, 16, 57, 6, 763, DateTimeKind.Utc).AddTicks(2138),
                            TransactionId = new Guid("550e8400-e29b-41d4-a716-446655440007"),
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("660e8400-e29b-41d4-a716-446655440003"),
                            Details = "Charged twice for same item",
                            EstimatedResolutionDate = new DateTime(2026, 2, 28, 16, 57, 6, 763, DateTimeKind.Utc).AddTicks(2152),
                            EvidenceAttached = false,
                            ReasonCode = 1,
                            Status = 2,
                            SubmittedAt = new DateTime(2026, 2, 27, 16, 57, 6, 763, DateTimeKind.Utc).AddTicks(2150),
                            TransactionId = new Guid("550e8400-e29b-41d4-a716-44665544000a"),
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        });
                });

            modelBuilder.Entity("CardDisputePortal.Core.Entities.Evidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DisputeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DisputeId");

                    b.ToTable("EvidenceFiles");
                });

            modelBuilder.Entity("CardDisputePortal.Core.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("MerchantCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerchantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440001"),
                            Amount = 1299.99m,
                            Currency = "ZAR",
                            Date = new DateTime(2026, 2, 14, 16, 57, 6, 762, DateTimeKind.Utc).AddTicks(3865),
                            MerchantCategory = "Online Retail",
                            MerchantName = "Takealot",
                            Reference = "TXN001",
                            Status = 0,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440002"),
                            Amount = 65.50m,
                            Currency = "ZAR",
                            Date = new DateTime(2026, 2, 15, 16, 57, 6, 762, DateTimeKind.Utc).AddTicks(5931),
                            MerchantCategory = "Food & Beverage",
                            MerchantName = "Seattle Coffee Co",
                            Reference = "TXN002",
                            Status = 0,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440003"),
                            Amount = 850.00m,
                            Currency = "ZAR",
                            Date = new DateTime(2026, 2, 16, 16, 57, 6, 762, DateTimeKind.Utc).AddTicks(5939),
                            MerchantCategory = "Fuel",
                            MerchantName = "Engen",
                            Reference = "TXN003",
                            Status = 0,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440004"),
                            Amount = 89.90m,
                            Currency = "ZAR",
                            Date = new DateTime(2026, 2, 17, 16, 57, 6, 762, DateTimeKind.Utc).AddTicks(5945),
                            MerchantCategory = "Food & Beverage",
                            MerchantName = "Steers",
                            Reference = "TXN004",
                            Status = 0,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440005"),
                            Amount = 2499.99m,
                            Currency = "ZAR",
                            Date = new DateTime(2026, 2, 18, 16, 57, 6, 762, DateTimeKind.Utc).AddTicks(5951),
                            MerchantCategory = "Retail",
                            MerchantName = "Mr Price Home",
                            Reference = "TXN005",
                            Status = 0,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440006"),
                            Amount = 125.50m,
                            Currency = "ZAR",
                            Date = new DateTime(2026, 2, 19, 16, 57, 6, 762, DateTimeKind.Utc).AddTicks(5956),
                            MerchantCategory = "Food & Beverage",
                            MerchantName = "KFC",
                            Reference = "TXN006",
                            Status = 0,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440007"),
                            Amount = 4999.99m,
                            Currency = "ZAR",
                            Date = new DateTime(2026, 2, 20, 16, 57, 6, 762, DateTimeKind.Utc).AddTicks(5991),
                            MerchantCategory = "Electronics",
                            MerchantName = "Incredible Connection",
                            Reference = "TXN007",
                            Status = 2,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440008"),
                            Amount = 567.89m,
                            Currency = "ZAR",
                            Date = new DateTime(2026, 2, 21, 16, 57, 6, 762, DateTimeKind.Utc).AddTicks(5996),
                            MerchantCategory = "Groceries",
                            MerchantName = "Pick n Pay",
                            Reference = "TXN008",
                            Status = 0,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440009"),
                            Amount = 199.00m,
                            Currency = "ZAR",
                            Date = new DateTime(2026, 2, 22, 16, 57, 6, 762, DateTimeKind.Utc).AddTicks(6026),
                            MerchantCategory = "Entertainment",
                            MerchantName = "Netflix",
                            Reference = "TXN009",
                            Status = 0,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-44665544000a"),
                            Amount = 1899.99m,
                            Currency = "ZAR",
                            Date = new DateTime(2026, 2, 23, 16, 57, 6, 762, DateTimeKind.Utc).AddTicks(6032),
                            MerchantCategory = "Retail",
                            MerchantName = "Sportsmans Warehouse",
                            Reference = "TXN010",
                            Status = 2,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-44665544000b"),
                            Amount = 234.50m,
                            Currency = "ZAR",
                            Date = new DateTime(2026, 2, 24, 16, 57, 6, 762, DateTimeKind.Utc).AddTicks(6038),
                            MerchantCategory = "Food & Beverage",
                            MerchantName = "Nandos",
                            Reference = "TXN011",
                            Status = 0,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-44665544000c"),
                            Amount = 178.99m,
                            Currency = "ZAR",
                            Date = new DateTime(2026, 2, 25, 16, 57, 6, 762, DateTimeKind.Utc).AddTicks(6043),
                            MerchantCategory = "Health & Beauty",
                            MerchantName = "Clicks",
                            Reference = "TXN012",
                            Status = 0,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-44665544000d"),
                            Amount = 725.00m,
                            Currency = "ZAR",
                            Date = new DateTime(2026, 2, 26, 16, 57, 6, 762, DateTimeKind.Utc).AddTicks(6049),
                            MerchantCategory = "Fuel",
                            MerchantName = "Shell",
                            Reference = "TXN013",
                            Status = 0,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-44665544000e"),
                            Amount = 899.99m,
                            Currency = "ZAR",
                            Date = new DateTime(2026, 2, 27, 16, 57, 6, 762, DateTimeKind.Utc).AddTicks(6054),
                            MerchantCategory = "Entertainment",
                            MerchantName = "Game",
                            Reference = "TXN014",
                            Status = 0,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        },
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-44665544000f"),
                            Amount = 189.50m,
                            Currency = "ZAR",
                            Date = new DateTime(2026, 2, 28, 16, 57, 6, 762, DateTimeKind.Utc).AddTicks(6060),
                            MerchantCategory = "Transport",
                            MerchantName = "Uber",
                            Reference = "TXN015",
                            Status = 0,
                            UserId = new Guid("550e8400-e29b-41d4-a716-446655440000")
                        });
                });

            modelBuilder.Entity("CardDisputePortal.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440000"),
                            CreatedAt = new DateTime(2026, 1, 30, 16, 57, 6, 760, DateTimeKind.Utc).AddTicks(3428),
                            Name = "Junior Moraba",
                            PhoneNumber = "0794935197"
                        });
                });

            modelBuilder.Entity("CardDisputePortal.Core.Entities.Dispute", b =>
                {
                    b.HasOne("CardDisputePortal.Core.Entities.Transaction", "Transaction")
                        .WithOne("Dispute")
                        .HasForeignKey("CardDisputePortal.Core.Entities.Dispute", "TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CardDisputePortal.Core.Entities.User", "User")
                        .WithMany("Disputes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardDisputePortal.Core.Entities.Evidence", b =>
                {
                    b.HasOne("CardDisputePortal.Core.Entities.Dispute", "Dispute")
                        .WithMany("EvidenceFiles")
                        .HasForeignKey("DisputeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispute");
                });

            modelBuilder.Entity("CardDisputePortal.Core.Entities.Transaction", b =>
                {
                    b.HasOne("CardDisputePortal.Core.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CardDisputePortal.Core.Entities.Dispute", b =>
                {
                    b.Navigation("EvidenceFiles");
                });

            modelBuilder.Entity("CardDisputePortal.Core.Entities.Transaction", b =>
                {
                    b.Navigation("Dispute");
                });

            modelBuilder.Entity("CardDisputePortal.Core.Entities.User", b =>
                {
                    b.Navigation("Disputes");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
